[package]
name = "win-move"
version = "0.2.0"
edition = "2018"

[dependencies.windows]
version = "0.36.1"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dwm",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_HiDpi"
]

[target.'cfg(windows)'.build-dependencies]
windows = "0.36.1"
winres = "0.1.12"
serde = "1.0"
serde_yaml = "0.8"
keyboard-types = "0.6.2"
