name: ci

on:
  pull_request:
    branches:
    - main

jobs:

  check_compilation:
    name: Check compilation
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- --no-deps -D warnings

