name: ci

on:
  pull_request:
    branches:
      - main
      - development

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Cargo fmt
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt

      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
