name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: windows-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release_please
        with:
          release-type: rust
          package-name: Win-Move

      - uses: actions/checkout@v2
        if: ${{ steps.release_please.outputs.release_created }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.54.0
          profile: minimal
          override: true
        if: ${{ steps.release_please.outputs.release_created }}

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --release
        if: ${{ steps.release_please.outputs.release_created }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_please.outputs.upload_url }}
          asset_path: target/release/win-move.exe
          asset_name: win-move.exe
          asset_content_type: application/octet-stream
        if: ${{ steps.release_please.outputs.release_created }}
